// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fibSum(num) {
	var value = 0;
	var prev = 1;
	var current = 2;
	while(current < num) {
		var next;
		if(current % 2 == 0){
			value += current;
		}
		next = current + prev;
		prev = current;
		current = next;
	}
	return value;
}

fibSum(4000000);